### ISSUE TITLE
k8s methods document should not be required

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/lando#152]
lando allows the methods document to be optional. `k8s.lando` fails with the following error when this is the case:
```
Running run_job_complete failed with Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/lando-0.9.3-py3.6.egg/lando/server/lando.py", line 365, in action_method
    getattr(actions, name)(payload)
  File "/usr/local/lib/python3.6/site-packages/lando-0.9.3-py3.6.egg/lando/k8s/lando.py", line 94, in run_job_complete
    self.organize_output_project()
  File "/usr/local/lib/python3.6/site-packages/lando-0.9.3-py3.6.egg/lando/k8s/lando.py", line 100, in organize_output_project
    job = self.manager.create_organize_output_project_job(methods_document.content)
AttributeError: 'NoneType' object has no attribute 'content'
```

**Comment by johnbradley** [comment]
Fixed by #134
