### ISSUE TITLE
Error running workflow

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/lando#180]
When attempting to run a workflow via lando worker image had the following error:
```
...
\'m sorry, I couldn\'t load this CWL file, try again with --debug for more information.\nThe error was: string indices must be integers
```

**Comment by johnbradley** [comment]
Ran with debug flag resulting in
```
I'm sorry, I couldn't load this CWL file.
The error was: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cwltool/main.py", line 675, in main
    tool = make_tool(uri, loadingContext)
  File "/usr/local/lib/python3.5/dist-packages/cwltool/load_tool.py", line 351, in make_tool
    tool = loadingContext.construct_tool_object(processobj, loadingContext)
  File "/usr/local/lib/python3.5/dist-packages/cwltool/workflow.py", line 55, in default_make_tool
    return Workflow(toolpath_object, loadingContext)
  File "/usr/local/lib/python3.5/dist-packages/cwltool/workflow.py", line 560, in __init__
    static_checker(workflow_inputs, workflow_outputs, step_inputs, step_outputs, param_to_step)
  File "/usr/local/lib/python3.5/dist-packages/cwltool/checker.py", line 164, in static_checker
    srcsf = sorted([p["pattern"] for p in src.get("secondaryFiles", [])])
  File "/usr/local/lib/python3.5/dist-packages/cwltool/checker.py", line 164, in <listcomp>
    srcsf = sorted([p["pattern"] for p in src.get("secondaryFiles", [])])
TypeError: string indices must be integers
```

**Comment by johnbradley** [comment]
I think this might be due to a problem with cwltool and not lando.
Using cwltool 1.0.20180912090223 caused the problem to go away.

**Comment by dleehr** [comment]
cwltool issue about this regression: https://github.com/common-workflow-language/cwltool/issues/1077

**Comment by johnbradley** [comment]
The current bespin worker image is deployed using `1.0.20190228155703`: https://github.com/Duke-GCB/gcb-ansible/blob/f095ff16db1dc907198a28bcacbcb2e2c3bd3715/bespin_infrastructure/bespin_worker/bespin_worker.yml#L11

Closing since this isn't an issue with lando.
