### ISSUE TITLE
Error Staging Data

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/lando#27]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/worker.py", line 189, in run
    self.func(working_directory, self.payload)
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/worker.py", line 77, in stage_files
    download_file.run(staging_context)
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/staging.py", line 116, in run
    duke_data_service = context.get_duke_data_service(self.user_id)
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/staging.py", line 46, in get_duke_data_service
    return DukeDataService(self.get_duke_ds_config(user_id))
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/staging.py", line 55, in get_duke_ds_config
    credentials = self.dds_user_credentials[user_id]
KeyError: 1
```

**Comment by johnbradley** [comment]
Forgot to send the bespin credentials to the worker when we switched to users giving the bespin credentials permission to download their files.
