### ISSUE TITLE
Install error: schema-salad conflicts with ruamel.yaml

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/lando#38]
Recently the installation broke.
```
python setup.py install
```
results in
```
error: ruamel.yaml 0.15.15 is installed but ruamel.yaml<=0.15.2,>=0.12.4 is 
  required by set(['schema-salad'])
```

**Comment by johnbradley** [comment]
Looks like this is an issue with cwltool:
```
virtualenv env
source env/bin/activate
pip install cwlref-runner==1.0
cwltool
```
Results in 
```
Traceback (most recent call last):
  File "/private/tmp/abc/env/bin/cwltool", line 11, in <module>
    sys.exit(main())
  File "/private/tmp/abc/env/lib/python2.7/site-packages/cwltool/main.py", line 661, in main
    _logger.info(versionfunc())
  File "/private/tmp/abc/env/lib/python2.7/site-packages/cwltool/main.py", line 574, in versionstring
    pkg = pkg_resources.require("cwltool")
  File "/private/tmp/abc/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 969, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/private/tmp/abc/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 860, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (ruamel.yaml 0.15.15 (/private/tmp/abc/env/lib/python2.7/site-packages), Requirement.parse('ruamel.yaml<=0.15.2,>=0.12.4'), set(['schema-salad']))
```

**Comment by johnbradley** [comment]
Created issue with cwltool https://github.com/common-workflow-language/cwltool/issues/449.
