### ISSUE TITLE
Error in Storing Output Step (Upload results to DukeDS)

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/lando#67]
The following error occurred storing the output of a job (in lando worker VM):
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/worker.py", line 179, in run
    self.func(working_directory, self.payload)
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/worker.py", line 107, in save_output
    project = save_job_output.run(source_directory)
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/staging.py", line 228, in run
    project = upload_project.run(config)
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/staging.py", line 201, in run
    project_upload.run()
  File "/usr/local/lib/python2.7/dist-packages/ddsc/core/upload.py", line 61, in run
    project_uploader.run(self.local_project)
  File "/usr/local/lib/python2.7/dist-packages/ddsc/core/projectuploader.py", line 119, in run
    self.upload_large_items()
  File "/usr/local/lib/python2.7/dist-packages/ddsc/core/projectuploader.py", line 153, in upload_large_items
    self.process_large_file(local_file, parent)
  File "/usr/local/lib/python2.7/dist-packages/ddsc/core/projectuploader.py", line 164, in process_large_file
    remote_id = file_content_sender.upload(self.settings.project_id, parent.kind, parent.remote_id)
  File "/usr/local/lib/python2.7/dist-packages/ddsc/core/fileuploader.py", line 57, in upload
    ParallelChunkProcessor(self).run()
  File "/usr/local/lib/python2.7/dist-packages/ddsc/core/fileuploader.py", line 221, in run
    wait_for_processes(processes, num_chunks, progress_queue, self.watcher, self.local_file)
  File "/usr/local/lib/python2.7/dist-packages/ddsc/core/util.py", line 314, in wait_for_processes
    raise ValueError(error_message)
ValueError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ddsc/core/fileuploader.py", line 290, in upload_async
    sender.send()
  File "/usr/local/lib/python2.7/dist-packages/ddsc/core/fileuploader.py", line 333, in send
    self._send_chunk(chunk, chunk_num)
  File "/usr/local/lib/python2.7/dist-packages/ddsc/core/fileuploader.py", line 345, in _send_chunk
    self.upload_operations.send_file_external(url_info, chunk)
  File "/usr/local/lib/python2.7/dist-packages/ddsc/core/fileuploader.py", line 142, in send_file_external
    resp = self._send_file_external_with_retry(http_verb, host, url, http_headers, chunk)
  File "/usr/local/lib/python2.7/dist-packages/ddsc/core/fileuploader.py", line 157, in _send_file_external_with_retry
    return self.data_service.send_external(http_verb, host, url, http_headers, chunk)
  File "/usr/local/lib/python2.7/dist-packages/ddsc/core/ddsapi.py", line 497, in send_external
    return self.http.put(host + url, data=chunk, headers=http_headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 560, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: SysCallError(104, 'ECONNRESET')",)
```

As you can see the error occurred sending data to the swift store. This error occurred as part of the `_send_file_external_with_retry` which retries 5 times with 1 second pauses between then raises this error.

**Comment by dleehr** [comment]
This is addressed by https://github.com/Duke-GCB/DukeDSClient/pull/177, which is part of lando via #85. I think it's fair to close this issue now, since in the worst case, the upload step can be retried from bespin.
