### ISSUE TITLE
lando worker instances cannot resolve their own hostname

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/lando#79]
On the current lando_worker_toil image, toil fails to start with the following error.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/worker.py", line 180, in run
    self.func(working_directory, self.payload)
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/worker.py", line 97, in run_workflow
    workflow.run(payload.cwl_file_url, payload.workflow_object_name, payload.job_order)
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/cwlworkflow.py", line 146, in run
    raise JobStepFailed(error_message + process.error_output, process.output)
JobStepFailed: 'CWL workflow failed with exit code: 1Traceback (most recent call last):
  File "/usr/local/bin/cwl-runner", line 7, in <module>
    from toil.cwl.cwltoil import main
  File "/usr/local/lib/python2.7/dist-packages/toil/cwl/cwltoil.py", line 21, in <module>
    from toil.job import Job
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 40, in <module>
    from toil.common import Toil, addOptions
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 532, in <module>
    def addOptions(parser, config=Config()):
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 75, in __init__
    setDefaultBatchOptions(self)
  File "/usr/local/lib/python2.7/dist-packages/toil/batchSystems/options.py", line 99, in setDefaultOptions
    config.mesosMasterAddress = \'%s:5050\' % getLocalIP()
  File "/usr/local/lib/python2.7/dist-packages/toil/batchSystems/options.py", line 23, in getLocalIP
    return socket.gethostbyname(socket.gethostname())
socket.gaierror: [Errno -2] Name or service not known
```

This behavior can be reproduced on the running VM with the following command:

```
$ python -c "import socket;socket.gethostbyname(socket.gethostname())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
```

Adding an entry to the hosts file with the full hostname allows it to resolve:

Original:
```
127.0.0.1 localhost 
```

Fixed:
```
127.0.0.1 localhost vm-job47-c6d0038a-3385-48ab-bd19-c3d2d5a03d8d
```

**Comment by dleehr** [comment]
Looks like there's a cloud-init option to manage /etc/hosts, so this would be addressed in lando_server

**Comment by johnbradley** [comment]
docs for `manage_etc_hosts`: http://cloudinit.readthedocs.io/en/latest/topics/modules.html?highlight=manage_etc_hosts#update-etc-hosts
