### ISSUE TITLE
cwlreport.py fails because file pair objects have no `path`

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/lando#96]
**updated root cause, see below**

[cwlreport.py](https://github.com/Duke-GCB/lando/blob/5456fe3ef698496614d143b7c5aafb40db9f0761/lando/worker/cwlreport.py#L166) attempts to extract the `path` of each output file in the CWL output, JSON , but the current build of lando worker with cwltoil 3.10.1 does not produce this key in file objects. It includes `location`, which is [also valid CWL](http://www.commonwl.org/v1.0/CommandLineTool.html#File)

> The `location` property of a File is a URI that uniquely identifies the file. Implementations must support the file:// URI scheme and may support other schemes such as http://. The value of `location` may also be a relative reference, in which case it must be resolved relative to the URI of the document it appears in. Alternately to `location`, implementations must also accept the `path` property on File, which must be a filesystem path available on the same host as the CWL runner (for inputs) or the runtime environment of a command line tool execution (for command line tool outputs).

Note that while `path` is a simple path, `location` is a URI.

Example from lando worker VM:

```
{
    "checksum": "sha1$xx", 
    "basename": "XXXXXX-dedup.bam", 
    "nameext": ".bam", 
    "nameroot": "XXXXXX-dedup", 
    "http://commonwl.org/cwltool#generation": 0, 
    "location": "file:///work/data_for_job_1/working/results/bams-markduplicates/XXXXXX-dedup.bam", 
    "secondaryFiles": [
        {
            "checksum": "sha1$yyy", 
            "basename": "XXXXXX-dedup.bai", 
            "nameroot": "XXXXXX-dedup", 
            "nameext": ".bai", 
            "http://commonwl.org/cwltool#generation": 0, 
            "location": "file:///work/data_for_job_1/working/results/bams-markduplicates/XXXXXX-dedup.bai", 
            "class": "File", 
            "size": 999
        }
    ], 
    "class": "File", 
    "size": 9999
}
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/worker.py", line 184, in run
    self.func(working_directory, self.payload)
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/worker.py", line 101, in run_workflow
    workflow.run(payload.cwl_file_url, payload.workflow_object_name, payload.job_order)
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/cwlworkflow.py", line 154, in run
    results_directory.add_files(process)
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/cwlworkflow.py", line 263, in add_files
    self._create_report(cwl_process)
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/cwlworkflow.py", line 296, in _create_report
    workflow_info.update_with_job_order(job_order_path=os.path.join(workflow_directory, self.job_order_filename))
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/cwlreport.py", line 158, in update_with_job_order
    input_param.set_value(self._create_str_value(val))
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/cwlreport.py", line 168, in _create_str_value
    return ','.join([WorkflowInfo._create_str_value(part) for part in val])
  File "/usr/local/lib/python2.7/dist-packages/lando/worker/cwlreport.py", line 166, in _create_str_value
    return val['path']
KeyError: 'path'
```

**Comment by dleehr** [comment]
I'll make this change

**Comment by dleehr** [comment]
Actually from the tests it looks like we were already expecting the field `location`, but expecting it to be a path (not a URI)

**Comment by dleehr** [comment]
I see, this is `update_with_job_order`, which does reads the job order - not the output.

**Comment by dleehr** [comment]
Upon further investigation, the issue is that cwlreport is trying to get the `path` out of a fastq file pair object like this:

```
{
  "file2": {
    "path": "XXXX_R2.fastq.gz", 
    "class": "File"
  }, 
  "file1": {
    "path": "XXXX_R2.fastq.gz", 
    "class": "File"
  }, 
  "name": "XXXX"
}
```
